name:                machinelearning
version:             0.1.0.0
github:              "AR2202/MLHaskell"
license:             BSD3
author:              "annika"
maintainer:          "annika.rings@freenet.de"
copyright:           "GPL"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/AR2202/MLHaskell/blob/master/README.md>

dependencies:
- base >= 4.7 && < 5
- vector
- cassava

library:
  source-dirs: src

executables:
  machinelearning-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - machinelearning

tests:
  machinelearning-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - machinelearning
